a Bash script that transfers a file from our client to a server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,14 +1,20 @@
 #!/usr/bin/env bash
-# Receiving an argument for an automatable task in bash script
-#arg1 = $1
-#arg2 = $2
-#arg3 = $3
-#arg4 = $4
-if [ "$#" -lt 3 ]; then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-elif [ "$#" -lt 4 ];
-then
-	scp -i "$1" "$3"@"$2":~/
+# This script transfers a file from our client to a server using scp
+
+if [ "$#" -lt 4 ]; then
+   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+   exit 1
+fi
+
+file_path=$1
+server_ip=$2
+username=$3
+ssh_key_path=$4
+
+scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip:~/"
+
+if [ $? -eq 0 ]; then
+   echo "File transferred successfully."
 else
-	scp -i "$4" "$1" "$3"@"$2":~/
+   echo "File transfer failed."
 fi
